#!/usr/bin/env bash
# =============================================================================
# Terraform Apply Script
# =============================================================================
# This script applies the Terraform plan:
#   1. Verify the plan file exists
#   2. Apply the plan (using the saved plan file)
#
# Usage: ./scripts/apply.sh [terraform_dir]
#   terraform_dir: Path to Terraform configuration (default: ./terraform)
#
# Important: This script applies the SAVED plan file, not a fresh plan.
# The plan file should have been:
#   1. Generated by plan.sh
#   2. Checked by policy_check.sh
#   3. Signed by sign_plan.sh
#   4. Verified by verify_plan.sh
# =============================================================================

set -euo pipefail

# Configuration
TERRAFORM_DIR="${1:-./terraform}"
PLAN_FILE="tfplan"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Verify terraform directory exists
if [[ ! -d "${TERRAFORM_DIR}" ]]; then
    log_error "Terraform directory not found: ${TERRAFORM_DIR}"
    exit 1
fi

# Change to terraform directory
cd "${TERRAFORM_DIR}"
log_info "Working directory: $(pwd)"

# Verify plan file exists
if [[ ! -f "${PLAN_FILE}" ]]; then
    log_error "Plan file not found: ${PLAN_FILE}"
    log_info "The plan file must be downloaded from the plan workflow artifacts."
    exit 1
fi

# Calculate hash of the plan file
PLAN_HASH=$(sha256sum "${PLAN_FILE}" | cut -d' ' -f1)
log_info "Plan file hash (SHA256): ${PLAN_HASH}"

# Initialize Terraform (needed to apply)
log_info "Initializing Terraform..."
terraform init -input=false

# Show what will be applied
log_info "Plan summary:"
echo ""
terraform show "${PLAN_FILE}" | head -50 || true
echo ""
echo "... (truncated for brevity)"
echo ""

# Apply the plan
log_info "Applying Terraform plan..."
echo ""
echo "=========================================="
echo "  TERRAFORM APPLY"
echo "=========================================="
echo ""

terraform apply -auto-approve "${PLAN_FILE}"

echo ""
echo "=========================================="
log_success "Terraform apply completed successfully!"

# Show outputs
log_info "Terraform outputs:"
terraform output || true

log_success "Infrastructure deployment complete!"
